### PR TITLE
Fixes URI Template when no query parameters specified.

### PR DESCRIPTION
**Pull request by freaz**

### CODE REVIEW

**Comment by smizell** [comment]
@freaz This looks good. Were there any fixtures that needed to be changed? If not, do you think we should add one?

**Comment by danielgtaylor** [comment]
LGTM :+1:

**Comment by freaz** [comment]
@smizell I didn't find it in feature fixtures. But it is in zoo example for instagram: https://github.com/apiaryio/swagger-zoo/blob/master/fixtures/examples/refract/instagram.json#L99

**Comment by smizell** [comment]
@freaz I see. That Instagram example isn't in the adapter fixtures. 

Also note, we usually try to add unpublished changes to the changelog file. Would you mind adding a note there with a note about the bugfix? Next would be to open a PR to bump version number and publish.

**Comment by freaz** [comment]
@smizell Yes sure.

**Pull request merged**
