### PR TITLE
Bump json-schema-faker to version 0.5.0-rc15

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Review by pksunkara — DISMISSED** [review]

**Comment by kylef** [comment]
This one's going to be a bit problematic due to some dependency problems:

Problematic Licenses: 7
> JSONSelect@0.4.0 (Custom: http://jsonselect.org) - license not pre-approved
> cjson@0.2.1 (MIT) - missing full license text
> colors@0.5.1 (Custom: http://i.imgur.com/goJdO.png) - license not pre-approved, missing full license text
> jison-lex@0.2.1 (UNKNOWN) - license not pre-approved
> jison@0.4.13 (Custom: http://github.com/zaach/jison/issues) - license not pre-approved
> nomnom@1.5.2 (Custom: http://nodejs.org/) - license not pre-approved, missing full license text
> underscore@1.1.7 (UNKNOWN) - license not pre-approved

I've filed a PR on jison so far but here is the list, I'll update with the status.

- [ ] JSONSelect
- [ ] cjson - Has valid license in repo, perhaps last release. One dependency needs to be updated upstream.
- [ ] colors
- [ ] jison-lex - https://github.com/zaach/jison-lex/issues/14
- [ ] jison  - filed https://github.com/zaach/jison/pull/366
- [ ] nomnom
- [ ] underscore - I believe this is resolved in newer versions, dependency needs to be updated upstream.

**Comment by kylef** [comment]
I believe https://github.com/dchester/jsonpath/pull/94 would resolve all of the licensing problems as it seems all of the problematic dependencies are introduced via jison. Looks like a much better solution.

**Review by kylef — CHANGES_REQUESTED** [review]
We need to resolve all of the dependency licensing problems before we're able to update this dependency.

**Comment by honzajavorek** [comment]
Mind there could be some false negatives in our license checking tool. Last time I recall inspecting `colors` and the current version has a license text IIRC, it just wasn't detected. It's a mess sometimes and needs manual digging and improving of the tool 😕

**Pull request closed without merging**
