### PR TITLE
Add support for x-summary and x-description

### PR DESCRIPTION
**Pull request by smizell**
Add support for x-summary and x-description on Path Item Objects.

### CODE REVIEW

**Comment by smizell** [comment]
cc @danielgtaylor

**Comment by pksunkara** [comment]
@smizell Why not use `_summary` and `_description`? or maybe even 2 underscores? `x-summary` looks like it's related to HTTP.

**Comment by kylef** [comment]
@pksunkara see http://swagger.io/specification/#vendorExtensions

**Comment by smizell** [comment]
This allows us to add titles and descriptions in places Swagger does not
allow. We are using Swagger's vendor extension and their naming, per
Adam's. story.

**Pull request merged**
