### PR TITLE
Release v0.8.0-pre.4

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

**Comment by freaz** [comment]
@pksunkara tests are failing. Also there is warning about console.log statement in `ast.js`

**Comment by freaz** [comment]
@pksunkara if console.log in ast.js is really intentional, then please ignore this warning (http://eslint.org/docs/rules/no-console)

**Comment by pksunkara** [comment]
@freaz I tried that. It messed up something with other eslint stuff.

**Comment by pksunkara** [comment]
Updated with ignoring the console warning

**Pull request merged**
