### PR TITLE
Removes extra slash in basePath

### PR DESCRIPTION
**Pull request by freaz**

### CODE REVIEW

**Comment by smizell** [comment]
One concern is that in correcting this, you may create another case where people do as follows:

```yaml
swagger: '2.0'
info:
  title: Swagger with extra slashes
basePath: '/api/'
paths:
  'resource':
    get:
      200:
        description: 'Success'
```

Do you think we should think about this, too?

**Comment by smizell** [comment]
Also, please remember to add this new fixture to Swagger Zoo :(

**Comment by freaz** [comment]
@smizell I think it's not possible defined only `resource` https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#paths-object.

Thanks for reminding zoo.

**Comment by smizell** [comment]
@freaz Great, thanks.

**Pull request merged**
