### PR TITLE
Release v0.8.0-pre.9

### PR DESCRIPTION
**Pull request by pksunkara**
Rebased beta branch over master

### CODE REVIEW

**Comment by pksunkara** [comment]
Please release after merge

**Comment by kylef** [comment]
@pksunkara Can you add a bit more context to what this PR is for?

**Comment by pksunkara** [comment]
It basically releases the new master branch stuff with the addition of auth support.

**Comment by kylef** [comment]
In that case, wouldn't we need to merge master into `shared/beta`? Otherwise changes such as #56 won't make it into the beta branch.

**Comment by pksunkara** [comment]
I rebased beta branch over master branch.

**Pull request merged**
